platform :ios, '9.0'

if ENV['/Users/shubham/AndroidStudioProjects/Xerneas/xerneas/xerneas/ios/Flutter'] == nil
  
end

target 'Runner' do
  # Pods for Runner
  pod 'Firebase/Firestore'
  pod 'GoogleMaps'
 



  # Flutter Pods
  pod 'Flutter', :path => ENV['/Users/shubham/AndroidStudioProjects/Xerneas/xerneas/xerneas/ios/Flutter']

  if File.exists? '../.flutter-plugins'
    flutter_root = File.expand_path('..')
    File.foreach('../.flutter-plugins') { |line|
      plugin = line.split(pattern='=')
      if plugin.length == 2
        name = plugin[0].strip()
        path = plugin[1].strip()
        resolved_path = File.expand_path("#{path}/ios", flutter_root)
        pod name, :path => resolved_path
      else
        puts "Invalid plugin specification: #{line}"
      end
    }
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end